// Plant data: approximate native ranges (by US state) and care instructions.
//
// Native ranges are simplified for illustration and based on general
// USDA PLANTS / Biota of North America Program (BONAP) range descriptions —
// good for a demo, but not a substitute for the official USDA PLANTS
// Database when making real planting decisions.

window.PLANTS = [
  {
    id: "eastern-redbud",
    commonName: "Eastern Redbud",
    scientificName: "Cercis canadensis",
    nativeStates: [
      "CT", "DE", "FL", "GA", "IL", "IN", "IA", "KS", "KY", "LA", "MD",
      "MI", "MS", "MO", "NE", "NJ", "NY", "NC", "OH", "OK", "PA", "SC",
      "TN", "TX", "VA", "WV",
    ],
    care: {
      sunlight: "Full sun to part shade",
      water: "Moderate — water regularly while young, drought-tolerant once established",
      soil: "Adaptable; prefers moist, well-drained soil",
      hardinessZones: "4b – 9a",
      bloomTime: "Early spring, before leaf-out",
      matureHeight: "20 – 30 ft",
      notes: "Understory tree; tolerates light shade well. Prune after flowering, not in fall/winter, to avoid losing next year's buds.",
    },
    description: "A small deciduous tree known for clusters of pink-purple flowers that appear directly on bare branches in early spring.",
  },
  {
    id: "purple-coneflower",
    commonName: "Purple Coneflower",
    scientificName: "Echinacea purpurea",
    nativeStates: [
      "AL", "AR", "GA", "IL", "IN", "IA", "KS", "KY", "LA", "MI", "MS",
      "MO", "NC", "OH", "OK", "SC", "TN", "VA", "WV", "WI",
    ],
    care: {
      sunlight: "Full sun",
      water: "Low to moderate — very drought-tolerant once established",
      soil: "Well-drained, tolerates poor/rocky soil",
      hardinessZones: "3 – 8",
      bloomTime: "Summer through early fall",
      matureHeight: "2 – 4 ft",
      notes: "Leave seed heads standing through winter — goldfinches and other birds feed on them.",
    },
    description: "A tough, long-blooming prairie perennial with large pink-purple daisy-like flowers and a spiky orange center cone.",
  },
  {
    id: "black-eyed-susan",
    commonName: "Black-Eyed Susan",
    scientificName: "Rudbeckia hirta",
    nativeStates: [
      "AL", "AZ", "AR", "CO", "CT", "DE", "FL", "GA", "IL", "IN", "IA",
      "KS", "KY", "LA", "ME", "MD", "MA", "MI", "MN", "MS", "MO", "MT",
      "NE", "NH", "NJ", "NM", "NY", "NC", "ND", "OH", "OK", "PA", "RI",
      "SC", "SD", "TN", "TX", "VT", "VA", "WV", "WI", "WY",
    ],
    care: {
      sunlight: "Full sun to light shade",
      water: "Low to moderate",
      soil: "Adaptable; tolerates average to poor soil",
      hardinessZones: "3 – 9",
      bloomTime: "Summer through fall",
      matureHeight: "1 – 3 ft",
      notes: "Self-seeds readily. Biennial or short-lived perennial — let some flowers go to seed to keep a patch going.",
    },
    description: "One of the most widespread North American wildflowers: bright yellow petals around a dark brown, dome-shaped center.",
  },
  {
    id: "butterfly-weed",
    commonName: "Butterfly Weed",
    scientificName: "Asclepias tuberosa",
    nativeStates: [
      "AL", "AZ", "AR", "CO", "CT", "FL", "GA", "IL", "IN", "IA", "KS",
      "KY", "LA", "ME", "MD", "MA", "MI", "MN", "MS", "MO", "NE", "NH",
      "NJ", "NM", "NY", "NC", "ND", "OH", "OK", "PA", "RI", "SC", "SD",
      "TN", "TX", "VT", "VA", "WV", "WI",
    ],
    care: {
      sunlight: "Full sun",
      water: "Low — very drought-tolerant, dislikes wet feet",
      soil: "Well-drained, sandy or rocky soil",
      hardinessZones: "3 – 9",
      bloomTime: "Early to late summer",
      matureHeight: "1 – 2.5 ft",
      notes: "A milkweed species — larval host plant for monarch butterflies. Slow to emerge in spring; taproot resents transplanting once established.",
    },
    description: "A milkweed relative with clusters of vivid orange flowers, a key nectar and host plant for monarch butterflies.",
  },
  {
    id: "california-poppy",
    commonName: "California Poppy",
    scientificName: "Eschscholzia californica",
    nativeStates: ["CA", "OR", "WA", "NV", "AZ", "NM"],
    care: {
      sunlight: "Full sun",
      water: "Low — thrives on winter/spring rain, drought-tolerant in summer",
      soil: "Well-drained, sandy or gravelly soil; poor soil is fine",
      hardinessZones: "8 – 10 (often grown as an annual elsewhere)",
      bloomTime: "Spring through summer",
      matureHeight: "8 – 12 in",
      notes: "Direct-sow; taproot doesn't transplant well. Closes its petals at night and on cloudy days.",
    },
    description: "California's state flower — silky, cup-shaped orange-gold blooms over feathery blue-green foliage.",
  },
  {
    id: "serviceberry",
    commonName: "Serviceberry (Downy)",
    scientificName: "Amelanchier arborea",
    nativeStates: [
      "AL", "CT", "DE", "FL", "GA", "IL", "IN", "IA", "KS", "KY", "LA",
      "ME", "MD", "MA", "MI", "MN", "MS", "MO", "NE", "NH", "NJ", "NY",
      "NC", "OH", "OK", "PA", "RI", "SC", "TN", "VT", "VA", "WV", "WI",
    ],
    care: {
      sunlight: "Full sun to part shade",
      water: "Moderate",
      soil: "Adaptable; prefers moist, well-drained soil",
      hardinessZones: "4 – 9",
      bloomTime: "Early spring",
      matureHeight: "15 – 25 ft",
      notes: "Edible summer berries attract birds fast. Good small tree for woodland edges and under power lines.",
    },
    description: "A small native tree with white spring flowers, edible summer berries, and reliable orange-red fall color.",
  },
  {
    id: "bee-balm",
    commonName: "Bee Balm (Scarlet)",
    scientificName: "Monarda didyma",
    nativeStates: [
      "CT", "DE", "GA", "IL", "IN", "KY", "ME", "MD", "MA", "MI", "NH",
      "NJ", "NY", "NC", "OH", "PA", "RI", "SC", "TN", "VT", "VA", "WV",
    ],
    care: {
      sunlight: "Full sun to part shade",
      water: "Moderate to high — likes consistently moist soil",
      soil: "Rich, moist, well-drained soil",
      hardinessZones: "4 – 9",
      bloomTime: "Summer",
      matureHeight: "2 – 4 ft",
      notes: "Prone to powdery mildew in still, humid air — give it good air circulation. Spreads by rhizomes; divide every few years.",
    },
    description: "A fragrant mint-family perennial with shaggy scarlet flower heads that hummingbirds and bees can't resist.",
  },
  {
    id: "little-bluestem",
    commonName: "Little Bluestem",
    scientificName: "Schizachyrium scoparium",
    nativeStates: [
      "AL", "AZ", "AR", "CO", "CT", "DE", "FL", "GA", "IL", "IN", "IA",
      "KS", "KY", "LA", "ME", "MD", "MA", "MI", "MN", "MS", "MO", "MT",
      "NE", "NH", "NJ", "NM", "NY", "NC", "ND", "OH", "OK", "PA", "RI",
      "SC", "SD", "TN", "TX", "UT", "VT", "VA", "WV", "WI", "WY",
    ],
    care: {
      sunlight: "Full sun",
      water: "Low — excellent drought tolerance once established",
      soil: "Adaptable; thrives in poor, dry, rocky soil",
      hardinessZones: "3 – 9",
      bloomTime: "Fluffy seed heads in late summer/fall",
      matureHeight: "2 – 4 ft",
      notes: "Warm-season bunchgrass — leave standing through winter for texture and wildlife cover, cut back in early spring.",
    },
    description: "A clumping native prairie grass, blue-green in summer and copper-orange in fall, valued for erosion control and winter interest.",
  },
  {
    id: "cardinal-flower",
    commonName: "Cardinal Flower",
    scientificName: "Lobelia cardinalis",
    nativeStates: [
      "AL", "AZ", "AR", "CO", "CT", "DE", "FL", "GA", "IL", "IN", "IA",
      "KS", "KY", "LA", "ME", "MD", "MA", "MI", "MN", "MS", "MO", "NE",
      "NH", "NJ", "NM", "NY", "NC", "ND", "OH", "OK", "PA", "RI", "SC",
      "SD", "TN", "TX", "UT", "VT", "VA", "WV", "WI",
    ],
    care: {
      sunlight: "Part shade to full sun (with consistent moisture)",
      water: "High — likes wet feet; great for pond/stream edges and rain gardens",
      soil: "Moist to wet, rich soil",
      hardinessZones: "3 – 9",
      bloomTime: "Mid to late summer",
      matureHeight: "2 – 4 ft",
      notes: "A favorite of hummingbirds. Short-lived perennial that self-seeds; keep soil consistently moist, never let it dry out.",
    },
    description: "A striking wetland-edge perennial with tall spikes of brilliant red tubular flowers.",
  },
  {
    id: "joe-pye-weed",
    commonName: "Joe-Pye Weed",
    scientificName: "Eutrochium purpureum",
    nativeStates: [
      "AL", "AR", "CT", "DE", "FL", "GA", "IL", "IN", "IA", "KS", "KY",
      "LA", "ME", "MD", "MA", "MI", "MN", "MS", "MO", "NE", "NH", "NJ",
      "NY", "NC", "OH", "OK", "PA", "RI", "SC", "TN", "VT", "VA", "WV",
      "WI",
    ],
    care: {
      sunlight: "Full sun to part shade",
      water: "Moderate to high — prefers consistently moist soil",
      soil: "Rich, moist soil; tolerates clay",
      hardinessZones: "4 – 8",
      bloomTime: "Mid to late summer",
      matureHeight: "4 – 7 ft",
      notes: "A magnet for butterflies. Give it room — it's a big, statuesque back-of-border plant.",
    },
    description: "A tall, stately native perennial with large dusty-pink flower domes that draw butterflies by the dozens.",
  },
  {
    id: "blanketflower",
    commonName: "Blanketflower",
    scientificName: "Gaillardia pulchella",
    nativeStates: [
      "AZ", "AR", "CO", "FL", "GA", "KS", "LA", "MS", "MO", "NE", "NM",
      "OK", "SC", "TX",
    ],
    care: {
      sunlight: "Full sun",
      water: "Low — excellent heat and drought tolerance",
      soil: "Well-drained, sandy soil; tolerates poor soil",
      hardinessZones: "2 – 11 (often grown as an annual in cold zones)",
      bloomTime: "Late spring through fall",
      matureHeight: "1 – 2 ft",
      notes: "Deadhead to prolong bloom. Avoid overly rich soil or overwatering, which causes floppy growth and rot.",
    },
    description: "A cheerful, heat-loving wildflower with red-and-yellow daisy blooms that flower nonstop all summer.",
  },
  {
    id: "prairie-blazing-star",
    commonName: "Prairie Blazing Star",
    scientificName: "Liatris pycnostachya",
    nativeStates: [
      "AR", "IL", "IN", "IA", "KS", "KY", "LA", "MN", "MS", "MO", "NE",
      "OK", "TX", "WI",
    ],
    care: {
      sunlight: "Full sun",
      water: "Moderate — tolerates both moist prairie soil and short dry spells",
      soil: "Adaptable; prefers moist, well-drained prairie soil",
      hardinessZones: "3 – 9",
      bloomTime: "Mid to late summer",
      matureHeight: "3 – 5 ft",
      notes: "Blooms top-down, unusual for a spike flower. A strong butterfly and bee attractor; corms are a favorite of voles/rodents.",
    },
    description: "A dramatic prairie native with dense purple flower spikes that bloom from the top down, unlike most spike-flowering plants.",
  },
];
